plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = 'com.lkzin'
version = '3.0.0'
base.archivesName = 'smartzombies-forge26.3'

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

minecraft {
    mappings channel: 'official', version: '26.3'
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            mods {
                smartzombies {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:26.3-66.0.9'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
