name: Build Smart Zombies Forge 26.3

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'

      - name: Verificar Java
        run: java -version

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.14.3'

      - name: Compilar Smart Zombies
        run: gradle build --no-daemon --stacktrace

      - name: Enviar JAR
        uses: actions/upload-artifact@v4
        with:
          name: SmartZombies-Forge26.3-JAR
          path: build/libs/*.jar
